version: "3"

services:
    cawebserver:
        image: docker.io/library/nginx:alpine-slim
        ports:
            - 8080:80
        volumes:
            - ./src/html:/usr/share/nginx/html
            - ./src/etc/nginx-ca.conf:/etc/nginx/nginx.conf:ro
            - ./src/etc/tls:/etc/nginx/tls:ro
    validatingwebserver:
        image: docker.io/library/nginx:alpine-slim
        ports:
            - 1443:443
        volumes:
            - ./src/html:/usr/share/nginx/html
            - ./src/etc/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./src/etc/tls:/etc/nginx/tls:ro
    optinalnocawebserver:
        image: docker.io/library/nginx:alpine-slim
        ports:
            - 2443:443
        volumes:
            - ./src/html:/usr/share/nginx/html
            - ./src/etc/nginx-optional_no_ca.conf:/etc/nginx/nginx.conf:ro
            - ./src/etc/tls:/etc/nginx/tls:ro
    brokenwebserver:
        image: docker.io/library/nginx:alpine-slim
        ports:
            - 3443:443
        volumes:
            - ./src/html:/usr/share/nginx/html
            - ./src/etc/nginx-brokenchain.conf:/etc/nginx/nginx.conf:ro
            - ./src/etc/tls:/etc/nginx/tls:ro